// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO1jmDiHDDryMJra12Cx9BkFbQvP2SK_M',
    appId: '1:1060087808650:web:d80072e35666f40be26373',
    messagingSenderId: '1060087808650',
    projectId: 'myproject-bb11b',
    authDomain: 'myproject-bb11b.firebaseapp.com',
    storageBucket: 'myproject-bb11b.appspot.com',
    measurementId: 'G-LY8C2NC85F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuz2ZXfRZf2axA4RcmdU9b4EsYpB16T4',
    appId: '1:1060087808650:android:d45fd11d8c1b996be26373',
    messagingSenderId: '1060087808650',
    projectId: 'myproject-bb11b',
    storageBucket: 'myproject-bb11b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoInr1ZjzPwc4FLvFtm_ZJystoSz7O6Y',
    appId: '1:1060087808650:ios:f92fad8f80d5bdd2e26373',
    messagingSenderId: '1060087808650',
    projectId: 'myproject-bb11b',
    storageBucket: 'myproject-bb11b.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
